extends:
- eslint:recommended
- plugin:import/recommended
- plugin:mozilla/recommended

env:
  es6: true

parserOptions:
  ecmaVersion: 6

root: true

rules:
  arrow-parens: off
  comma-dangle: off
  function-paren-newline: off
  guard-for-in: off
  import/no-named-as-default: off
  import/prefer-default-export: off
  linebreak-style: off
  no-multi-assign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-use-before-define: off
  object-curly-newline: off
  no-console: off
