#+TITLE: Emacs configuration file
#+AUTHOR: Auralcat
#+DATE: 2017:05:17
#+LANGUAGE: en

* Startup
  #+BEGIN_SRC emacs-lisp :tangle yes
    ;; Start in scratch buffer

    ;; Set fallback font
    (set-face-attribute 'default nil :font "Ubuntu Mono" :height 120)
  #+END_SRC

* Environment Customizations
#+BEGIN_SRC emacs-lisp :tangle yes
  ;; Change window title
  (setq frame-title-format '("Yes, this is Emacs!"))

  ;; A small performance improvement
  (setq redisplay-dont-pause t)

  ;; Store all backups in a specific folder:
  (setq backup-directory-alist `(("." . "~/file-bouncer/emacs-backups")))

  ;; Manual packages load path
  (add-to-list 'load-path "~/my-dotfiles/.emacs.d/manual-packages/emacs-solargraph/")

  ;; Backup files by copying them
  (setq backup-by-copying t)

  ;; I'm too lazy to type "yes" or "no"
  (fset 'yes-or-no-p 'y-or-n-p)

  ;; Clean whitespace before saving a file
  (add-hook 'before-save-hook (quote whitespace-cleanup))

  ;; Allow only one theme at a time
  (setq custom-theme-allow-multiple-selections nil)

  ;; Enable ido-mode (fewer keystrokes to switch buffers!)
  (ido-mode 1)

  ;; Easier mark cycling, both local and global
  (setq set-mark-command-repeat-pop t)

  ;; ido-mode in the minibuffer
  (icomplete-mode 1)

  ;; Enable windmove (switch windows with Shift+Arrow keys)
  (when (fboundp 'windmove-default-keybindings)
      (windmove-default-keybindings))

  ;; Replace the built-in buffer menu with ibuffer
  (global-set-key [24 2] (quote ibuffer))

  ;; Prevent the scratch buffer from being killed
  (with-current-buffer "*scratch*"
      (emacs-lock-mode 'kill))

  ;; Enable auto-revert-mode
  (global-auto-revert-mode t)

  ;; Remove the menu bar in terminal mode
  (when (not (display-graphic-p))
    (menu-bar-mode -1))

  ;; ;; Use alternate icon fonts when available
  ;; (add-to-list 'load-path "~/.local/share/icons-in-terminal/")

  ;; Use Bash as default shell interpreter
  (setq org-babel-sh-command "/bin/bash")

  ;; Activate Company mode
  (add-hook 'after-init-hook 'global-company-mode)

  ;; Enable global Abbrev mode
  (setq-default abbrev-mode t)

  ;; Save last edited place in files
  (require 'saveplace)
  (setq-default save-place t)
  ;; (save-place-mode 1)
#+END_SRC

#+RESULTS:
: t

* Dired
  #+BEGIN_SRC emacs-lisp :tangle yes
  ;; Use dired asynchronously
  (autoload 'dired-async-mode "dired-async.el" nil t)
  (dired-async-mode 1)
  #+END_SRC
* Personal info
  #+BEGIN_SRC emacs-lisp :tangle yes
    ;; Load from external file.
    (load "~/.emacs.secrets")
  #+END_SRC

* Hooks
#+BEGIN_SRC emacs-lisp :tangle yes
;; Prog-mode is from where all the programming modes are derived from.
;; This means that if you call prog-mode-hook, the settings will be
;; applied to ALL programming modes in Emacs.
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
(add-hook 'text-mode-hook 'column-number-mode)

;; Ruby
;; Activate ruby-tools
(add-hook 'enh-ruby-mode-hook (quote ruby-tools-mode))

;; Create filling for org-mode
(add-hook 'org-mode-hook 'auto-fill-mode)
#+END_SRC
* IRC
Qui Nov  2 19:57:06 BRST 2017 - Tried using IRC inside Emacs, didn't please
me, too many buffers to work with... for now.
#+BEGIN_SRC emacs-lisp :tangle yes
;; Use Weechat from Emacs
(use-package weechat)
;; Bind M-p to switch to previous buffer
#+END_SRC
* Custom functions
#+BEGIN_SRC emacs-lisp :tangle yes
;; Recreate scratch buffer
(defun create-scratch-buffer ()
  "create a scratch buffer"
  (interactive)
  (switch-to-buffer (get-buffer-create "*scratch*"))
  (org-mode)
  (insert initial-scratch-message)
  ;; Prevent the scratch buffer from being killed
  (with-current-buffer "*scratch*"
      (emacs-lock-mode 'kill)))

;; Unfill region, AKA leave single huge line
(defun unfill-region (beg end)
  "Unfill the region, joining text paragraphs into a single
  logical line.  This is useful, e.g., for use with
  `visual-line-mode'."
  (interactive "*r")
    (let ((fill-column (point-max)))
      (fill-region beg end)))

;; Call the live page reload script from within Emacs and bind it to a key
;; (defun css-live-reload-current-webpage ()
;;     (when (and (stringp buffer-file-name)
;;       (string-match "\\.scss\\'" buffer-file-name))
;;     (shell-command "~/my-dotfiles/bash/live-reload-firefox.sh")))

;; The original idea is to call this function when saving a stylesheet
;; (add-hook 'after-save-hook 'css-live-reload-current-webpage)

#+END_SRC
* Function Aliases
#+BEGIN_SRC emacs-lisp :tangle yes
;; This is how you define aliases for Elisp functions
(defalias 'plp 'package-list-packages)
#+END_SRC
* Packages
** Major Modes
*** Sass-mode
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package sass-mode
       ;; Set Sass mode for SASS files and Css mode for SCSS files.
       :config
       (add-to-list 'auto-mode-alist
      '("\\.sass\\'" . sass-mode)))

    #+END_SRC
*** SCSS-mode
    Major mode for SCSS files, together with Sass.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package scss-mode

       :config
       (add-to-list 'auto-mode-alist
      '("\\.scss\\'" . scss-mode)))
    #+END_SRC

*** Js2-mode
    A better default Javascript mode
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package js2-mode)

      ;; Set js2-mode as default mode for JS files
      (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))

      (defun js2-mode-tweaks ()
      ;; Use company-yas as main backend
        (set (make-local-variable 'company-backends) '(company-yasnippet company-etags company-capf))
        (company-mode t))

      (add-hook 'js2-mode-hook 'js2-mode-tweaks)

       ;; Replacing Tern with ac-js2 and js2-refactor
       (use-package ac-js2)
       (use-package js2-refactor
       :diminish js2-refactor-mode)

       ;; Add to js2-mode
       (add-hook 'js2-mode-hook #'js2-refactor-mode)
       (js2r-add-keybindings-with-prefix "C-c r")

      ;; Set syntax highlight level
      (setq js2-highlight-level 3)
    #+END_SRC

    #+RESULTS:
    : 3

*** PHP-mode
    PHP support for Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package php-mode)
    (add-hook 'php-mode-hook (lambda() (add-to-list 'company-backends 'company-php)))
    #+END_SRC
*** Enhanced-ruby-mode
    A better ruby-mode.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package enh-ruby-mode)

    ;; Set it as default mode for Ruby files
    (add-to-list 'auto-mode-alist
    '("\\(?:\\.rb\\|ru\\|rake\\|thor\\|jbuilder\\|gemspec\\|podspec\\|/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Vagrant\\|Guard\\|Pod\\)file\\)\\'"
    . enh-ruby-mode))
    #+END_SRC
*** Web Mode
    I use this for HTML files mostly, works good for PHP too.
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package web-mode :ensure t
      :bind (:map web-mode-map
    ("C-<up>"    . web-mode-element-previous)
    ("C-<down>"  . web-mode-element-next)
    ("C-<left>"  . web-mode-element-beginning)
    ("C-<right>" . web-mode-tag-match)
    ("C-S-<up>"  . web-mode-element-parent)
    ("M-<up>"    . web-mode-element-content-select)
    ("C-k"       . web-mode-element-kill)))

      ;; File associations
      (add-to-list 'auto-mode-alist '("\\.phtml\\'"  . web-mode))
      (add-to-list 'auto-mode-alist '("\\.php\\'"    . web-mode))
      (add-to-list 'auto-mode-alist '("\\.erb\\'"    . web-mode))
      (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
      (add-to-list 'auto-mode-alist '("\\.html?\\'"  . web-mode))
      (add-to-list 'auto-mode-alist '("\\.vue?\\'"   . web-mode))

      ;; Engine associations
      (setq web-mode-engines-alist
      '(("php"    . "\\.phtml\\'")
      ("blade"  . "\\.blade\\.")))

      ;; Highlight tag when editing
      (setq web-mode-enable-current-element-highlight t)

    #+END_SRC
*** YAML-mode
    YAML support for Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package yaml-mode :ensure t)
    #+END_SRC
*** CSV-mode
    CSV support for Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package csv-mode)
    #+END_SRC
** Minor Modes
*** Alchemist
    Elixir helper package integration for Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package alchemist :ensure t)
      ;; Activate it in Elixir mode
      (add-hook 'elixir-mode-hook 'alchemist-mode)
    #+END_SRC
*** Projectile
    Manage projects in Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package projectile
       :init
       (setq projectile-keymap-prefix (kbd "C-c p")))
       ;; Enable it
       (add-hook 'after-init-hook #'projectile-global-mode)
    #+END_SRC
*** Autopair
   Automatically pair braces and quotes like in TextMate
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package autopair
      :init (autopair-global-mode))
   #+END_SRC
*** Emmet-mode
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package emmet-mode)
    #+END_SRC
*** Highlight-numbers mode
    Sets font lock faces to numbers in Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package highlight-numbers)
    (add-hook 'prog-mode-hook 'highlight-numbers-mode)
    #+END_SRC
*** Flycheck
    Syntax checker, replaces flymake
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package flycheck
       :config
       ;; turn on flychecking globally
       (add-hook 'after-init-hook #'global-flycheck-mode))
    #+END_SRC
*** Ruby Tools
    Goodies for Ruby programming modes.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package ruby-tools)
    #+END_SRC
*** Evil Mode
    Yes, I'm committing this heresy
    #+BEGIN_SRC emacs-lisp :tangle yes
    #+END_SRC
**** Evil-leader
     Add a prefix key to Evil mode, like the Leader key in Vim.
     #+BEGIN_SRC emacs-lisp :tangle yes
     (use-package evil-leader)
     (global-evil-leader-mode)
     ;; Evil mode needs to be loaded after evil-leader
     (use-package evil)
     (evil-mode 1)

     ;; Load configs
     (load "~/my-dotfiles/.emacs.d/evilrc")
     #+END_SRC
**** Evil Surround
     Easier manipulation of delimiters, emulation of vim.surround
     #+BEGIN_SRC emacs-lisp :tangle yes
     (use-package evil-surround)
     (global-evil-surround-mode)
     #+END_SRC
*** Helm
     Incremental completion and selection narrowing framework
     #+BEGIN_SRC emacs-lisp :tangle yes
     (use-package helm)
     (require 'helm-config)
     (helm-mode 1)

     ;; Bind the keys I want:
     (global-set-key (kbd "M-x") 'helm-M-x)
     (global-set-key (kbd "»") 'helm-M-x)
     (global-set-key (kbd "C-x C-f") 'helm-find-files)
     (global-set-key (kbd "C-x b") 'helm-buffers-list)

     ;; Enable fuzzy matching
     (setq helm-M-x-fuzzy-match t)
     #+END_SRC

*** Company
**** Main Config
     *COMPlete ANYthing* inside Emacs.
     I switched to it because it works in GUI Emacs and auto-complete doesn't.
     #+BEGIN_SRC emacs-lisp :tangle yes
       (use-package company)

       ;; Web-mode needs HTML and CSS completions.
       ;; JS is not satisfactory at this point IMO

       (defun web-mode-tweaks ()
       (require 'company-web-html)
       (set (make-local-variable 'company-backends) '(company-web-html company-css))
       (emmet-mode 1)
       (company-mode t))

       ;; Add tweaks
       (add-hook 'web-mode-hook 'web-mode-tweaks)

       ;; Autocompletion for Bootstrap/FontAwesome classes
       (use-package ac-html-bootstrap)

       ;; Web-mode completions
       (use-package company-web)

       ;; Company statistics package
       (use-package company-statistics)
       (company-statistics-mode)

       ;; Company with prescient.el offers better sorting of completion candidates.
       ;; I don't know if it clashes with company-statistics.
       (use-package company-prescient)

       ;; Activate it
       (company-prescient-mode)
     #+END_SRC

     #+RESULTS:
     : t

**** Front-ends
***** Company-box
      Show icons in Company tooltip and different backends.
      #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package company-box
    :diminish company-box-mode
    :if window-system
    :hook (company-mode . company-box-mode))

    ;; Add alternate icon font
    (add-to-list 'load-path "~/.local/share/icons-in-terminal/")

    ;; Temporary fix
    (add-to-list 'load-path "~/.emacs.d/manual-packages/font-lock+/")
    (require 'font-lock+)
    (require 'icons-in-terminal)

    (setq company-box-icons-unknown 'fa_question_circle)

    (setq company-box-icons-elisp
    '((fa_tag :face font-lock-function-name-face) ;; Function
    (fa_cog :face font-lock-variable-name-face) ;; Variable
    (fa_cube :face font-lock-constant-face) ;; Feature
    (md_color_lens :face font-lock-doc-face))) ;; Face

    (setq company-box-icons-yasnippet 'fa_bookmark)
      #+END_SRC
*** Keyfreq
    Shows most used commands in editing session.
    To see the data, run (keyfreq-show) with M-:
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package keyfreq)

    ;; Ignore arrow commands and self-insert-commands
    (setq keyfreq-excluded-commands
    '(self-insert-command
    org-self-insert-command
    abort-recursive-edit
    company-ignore
    forward-char
    backward-char
    previous-line
    next-line))

    ;; Activate it
    (keyfreq-mode 1)
    (keyfreq-autosave-mode 1)
    #+END_SRC
*** Diminish
    Free some space in the mode line removing superfluous mode indications.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package diminish :ensure t
       ;; These are loaded at startup
       :diminish helm-mode
       :diminish company-mode
       :diminish undo-tree-mode
       :diminish auto-revert-mode
       :diminish auto-fill-function
       :diminish abbrev-mode
       :diminish autopair-mode)
    ;; These are loaded at other moments
    (eval-after-load "editorconfig" '(diminish 'editorconfig-mode))
    (eval-after-load "yasnippet" '(diminish 'yas-minor-mode))
    #+END_SRC
*** Editorconfig
    Helps developers define and maintain consistent coding styles
    between different editors and IDEs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package editorconfig
       :init
       ;; Activate it.
       (editorconfig-mode 1))
    #+END_SRC
*** Nyan-mode
    Put a Nyan Cat in your mode line! :3
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package nyan-mode)
    (nyan-mode 1)
    #+END_SRC
*** Mode Icons
    Indicate modes in the mode line using icons
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package mode-icons
       :init
       (mode-icons-mode))
    #+END_SRC
*** Emojify
    Add emoji support for Emacs
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package emojify)
    #+END_SRC
** Utilities
*** Evil-numbers
    Increment and decrement numbers like in Vim.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package evil-numbers
    :bind ("C-c <up>" . evil-numbers/inc-at-pt)
          ("C-c <down>" . evil-numbers/dec-at-pt))
    #+END_SRC

    #+RESULTS:
    : evil-numbers/dec-at-pt


*** YATemplate
    Templating in Emacs made easier. Uses auto-insert-mode too.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package yatemplate
    :ensure t
    :init
    (setq yatemplate-dir "~/.emacs.d/templates")
    (yatemplate-fill-alist)
    (auto-insert-mode 1))
    #+END_SRC

*** Evil-Matchit
    Adds more matching objects for the % operator in evil, such as
    def-end in Ruby/Python and HTML tags.
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package evil-matchit
    :ensure t
    :init
    (global-evil-matchit-mode 1))
    #+END_SRC
*** XTerm Color
    Better shell colorization.
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package xterm-color
    :ensure t
    :requires (eshell)
    :config
    (;; Add filter function to pre-output
     (add-to-list 'eshell-preoutput-filter-functions 'xterm-color-filter)
     (setq eshell-output-filter-functions (remove 'eshell-handle-ansi-color eshell-output-filter-functions))
     ;; Set eshell $TERM envvar to xterm-256color
     (setenv "TERM" "xterm-256color")))

      (add-hook 'eshell-before-prompt-hook
    (lambda ()
      (setq xterm-color-preserve-properties t)))


    #+END_SRC

    #+RESULTS:
    | lambda | nil | (setq xterm-color-preserve-properties t) |

*** Cheat.sh client
    Access cheat.sh from Emacs
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package cheat-sh :ensure t)
    #+END_SRC
*** Writeroom Mode
    Dims the modeline, perfect for focusing on writing text/code
    #+BEGIN_SRC emacs-lisp :tangle yes
      (use-package writeroom-mode :ensure t)
      ;; Activate it manually, it doesn't play well with Moe modeline globally
    #+END_SRC
*** Restart Emacs
    Restart Emacs from within Emacs
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package restart-emacs)
    #+END_SRC
*** ReST Client
    Use it like Postman, but inside Emacs!
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package restclient)
    #+END_SRC
*** Helm-projectile
    Browse through Projectile commands using Helm.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package helm-projectile)
    ;; Activate it.
    (helm-projectile-on)
    #+END_SRC
*** Rainbow Delimiters
    Highlight parentheses, brackets and braces according to their
    depth.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package rainbow-delimiters)
    ;; Add this to prog-mode
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
    #+END_SRC
*** Smart Mode Line
    Prettier mode line.
    You can activate it with M-x sml/setup.
    #+BEGIN_SRC emacs-lisp :tangle yes
    ;; Smart-mode-line depends on powerline
    (use-package powerline :ensure t)

    #+END_SRC
*** Web-beautify
    Format HTML/CSS and JS code with js-beautify
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package web-beautify)
    #+END_SRC
*** Magit
    How to win at Git from Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package magit)
    #+END_SRC
*** Eshell configurations
    #+BEGIN_SRC emacs-lisp :tangle yes
    ;; Eshell extras
    (use-package eshell-prompt-extras)

    ;; More configs
    (with-eval-after-load "esh-opt"
    (autoload 'epe-theme-lambda "eshell-prompt-extras")
    (setq eshell-highlight-prompt t
    eshell-prompt-function 'epe-theme-lambda))
    #+END_SRC
*** Yasnippets
    It originally came with company-mode, it's handy to write faster
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package yasnippet-snippets)
    #+END_SRC
*** Circadian
    Theme changer for Emacs.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package circadian
      :ensure t
      :config
      (setq circadian-themes '((:sunrise . moe-light)
                               (:sunset  . jazz)))

      (circadian-setup))
    #+END_SRC
*** Ace Jump Mode
    Move to any word with 2 keypresses.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package ace-jump-mode)
    #+END_SRC
*** Robe
    Ruby's autocomplete, navigation and project tools, especially for
    Rails.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package robe)
    (add-hook 'enh-ruby-mode-hook 'robe-mode)

    ;; Integrate with Company
    (eval-after-load 'company '(push 'company-robe company-backends))
    #+END_SRC
*** RVM
    Ruby Version Manager. Akin to python's virtualenv.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package rvm)
    #+END_SRC
*** Anzu
    Show search result count in the mode line.
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package evil-anzu)
    (global-anzu-mode)
    #+END_SRC
*** Vagrant TRAMP
    Open files in running Vagrant box using TRAMP
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package vagrant-tramp)
    #+END_SRC
* Themes
** Jazz
   A warm theme with dark colors.
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package jazz-theme :ensure t
   :defer t)
   #+END_SRC
** Moe
   Light and dark theme, with some extra stuff.
   Comes with support for smart-mode-line.
   #+BEGIN_SRC emacs-lisp :tangle yes
     (use-package moe-theme
      :ensure t
      :config
      ;; I just want to touch the theme, don't use it
      (moe-dark)
      (disable-theme 'moe-dark)
      (powerline-moe-theme)
      ;; Choose a color for the mode line (Default: blue)
      (moe-theme-set-color 'yellow))
   #+END_SRC

   #+RESULTS:
   : t

** Abyss
   Dark contrast theme
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package abyss-theme :ensure :defer t)
   #+END_SRC
** Github Modern
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package github-modern-theme :ensure :defer t)
   #+END_SRC
** IntelliJ
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package intellij-theme :ensure :defer t)
   #+END_SRC
** Doom Themes
   A collection of themes from the Doom package
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package doom-themes :ensure :defer t)
   #+END_SRC
* Graphical
#+BEGIN_SRC emacs-lisp :tangle yes
;; Set font in graphical mode
(when (display-graphic-p)
    ;; Use Fantasque Sans Mono when available
    (if (member "Fantasque Sans Mono" (font-family-list))
    (set-face-attribute (quote default) nil :font "Fantasque Sans Mono" :height 120)
    '(set-face-attribute (quote default) nil :font "Ubuntu Mono" :height 120))

    ;; Remove menu and scroll bars in graphical mode
    (menu-bar-mode 0)
    (tool-bar-mode 0)
    (scroll-bar-mode 0)
    ;; Enable emoji images
    (global-emojify-mode)
    ;; Enable them in the mode line as well.
    (global-emojify-mode-line-mode)
    ;; Maximize frame on startup
    (toggle-frame-maximized))
#+END_SRC

#+RESULTS:

* Keybindings
#+BEGIN_SRC emacs-lisp :tangle yes
  ;; Remapping the help hotkey so it doesn't clash with Unix backspace.
  ;; Whenever you want to call help you can use M-x help as well. F1
  ;; works too.
  ;; (define-key key-translation-map [?\C-h] [?\C-?])

  ;; Use the menu key for helm-m-x
  (global-set-key [menu] (quote helm-M-x))

  ;; Unfill region
  (define-key global-map "\C-\M-q" 'unfill-region)

  ;; Switch to last buffer - I do it all the time
  (global-set-key [27 112] (quote mode-line-other-buffer))

  ;; Save buffer with F5
  (global-set-key [f5] (quote save-buffer))

  ;; Mapping AltGr-d to delete-other-windows,
  ;; Another symbol I don't use often.
  (global-set-key [240] (quote delete-other-windows))

  ;; Access buffers with Alt-Gr b
  (global-set-key [8221] (quote ido-switch-buffer))

  ;; Map the Home and End keys to go to the beginning and end of the buffer
  (global-set-key [home] (quote beginning-of-buffer))
  (global-set-key [end] (quote end-of-buffer))

  ;; Move to beginning of line or indentation
  (defun back-to-indentation-or-beginning () (interactive)
    (if (= (point) (progn (back-to-indentation) (point)))
    (beginning-of-line)))

  (global-set-key (kbd "C-a") (quote back-to-indentation-or-beginning))

  ;; Hippie-Expand: change key to M-SPC; Replace dabbrev-expand
  (global-set-key "\M- " 'hippie-expand)
  (global-set-key "\M-/" 'hippie-expand)

  ;; Eshell - bind M-p to go back to previous buffer
  (defun eshell-tweaks ()
      "Keybindings for the Emacs shell"
      (local-set-key (kbd "M-p") 'switch-to-prev-buffer)
      "Start in Emacs mode"
      (evil-set-initial-state 'eshell-mode 'emacs))
  (add-hook 'eshell-mode-hook 'eshell-tweaks)

  ;; Set C-x j to go to current clocked task in org-mode
  (global-set-key (kbd "C-x j") 'org-clock-goto)

#+END_SRC
* Web-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(defun web-mode-keybindings ()
    "Define mode-specific keybindings like this."
    (local-set-key (kbd "C-c C-v") 'browse-url-of-buffer)
    (local-set-key (kbd "C-c /") 'sgml-close-tag))

;; Add company backends when loading web-mode.
(defun web-mode-company-load-backends ()
    (company-web-bootstrap+)
    (company-web-fa+))

(add-hook 'web-mode-hook 'web-mode-keybindings)
(add-hook 'web-mode-hook 'web-mode-company-load-backends)
#+END_SRC
* Org-mode
#+BEGIN_SRC emacs-lisp :tangle yes
  ;; We don't need Flycheck in org-mode buffers. Usually.
  (add-hook 'org-mode-hook '(lambda() (flycheck-mode 0)))

  ;; Keep agenda file list in a single file so I can publish my config.
  ;; DO NOT use C-c [ or C-c ] to add/remove files to the agenda otherwise
  ;; Emacs will write the var to init.el
  (setq org-agenda-files "~/file-bouncer/org-agenda-file-list.org")

  ;; Bind org-capture to C-c c
  (global-set-key (kbd "\C-c c") (quote org-capture))

  ;; Bind org-pomodoro to C-x p
  (global-set-key (kbd "\C-x p") (quote org-pomodoro))

  ;; Open subheading with C-c RET and invert with M-RET
  (local-set-key [27 13] (quote org-ctrl-c-ret))
  (local-set-key [3 13] (quote org-insert-subheading))

  ;; Org-agenda: point the files you want it to read
  ;; (setq org-agenda-files (list "~/file-bouncer/org-files/contact-based-system/"))

  ;; Change default diary location
  (setq diary-file "~/emacs-diary")

  ;; Use diary entries in org-agenda
  (setq org-agenda-include-diary t)

  ;; Use C-RET to complete words in Org-mode
  (local-set-key [C-return] (quote complete))

  ;; Always respect the content of a heading when creating todos!
  (local-set-key [M-S-return] (quote org-insert-todo-heading-respect-content))

  ;; Map C-S-enter to org-insert-todo-subheading
  (local-set-key [C-S-return] (quote org-insert-todo-subheading))

#+END_SRC

#+RESULTS:
: org-insert-todo-subheading

** Org-bullets
   Change org-mode's *s to UTF-8 chars
   #+BEGIN_SRC emacs-lisp :tangle yes
   (use-package org-bullets
      :init
      (add-hook 'org-mode-hook (lambda() (org-bullets-mode 1))))
   #+END_SRC
** Org-babel
*** Elixir
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package ob-elixir)
    #+END_SRC
*** Emacs' restclient-mode
    #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package ob-restclient)
    #+END_SRC

*** Load languages
   #+BEGIN_SRC emacs-lisp :tangle yes
     (org-babel-do-load-languages
     'org-babel-load-languages
     '(
     ;; (sh . t)
    (python . t)
    (ruby . t)
    (elixir . t)
    (plantuml . t)
    (dot . t)
     ))
   #+END_SRC

* Variables
#+BEGIN_SRC emacs-lisp :tangle yes
;; Set Org mode as default mode for new buffers:
(setq-default major-mode 'org-mode)

;; Enable auto-fill mode by default
(auto-fill-mode 1)

;; Set default fill to 79
(set-fill-column 79)

;; Set line number mode and column number mode for code files
(line-number-mode 1)

;; Change tab width and change tabs to spaces
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)

;; Making Emacs auto-indent
(define-key global-map (kbd "RET") 'newline-and-indent)

;; Shows trailing whitespace, if any:
(setq-default show-trailing-whitespace t)
;; Don't do that for terminal mode!
(add-hook 'multi-term-mode-hook (setq-default show-trailing-whitespace nil))

(defun css-mode-tweaks()
  (emmet-mode 1)
  (rainbow-mode 1))

;; Emmet-mode: activate for html-mode, sgml-mode,
;; css-mode, web-mode and sass-mode
(add-hook 'sgml-mode-hook 'emmet-mode)
(add-hook 'sass-mode-hook 'css-mode-tweaks)
(add-hook 'web-mode-hook 'emmet-mode)

;; By the way, it's nice to add rainbow-mode for CSS
(add-hook 'css-mode-hook 'css-mode-tweaks)

;; Python: use python3 as default shell interpreter
(setq python-shell-interpreter "python3")

#+END_SRC
* Macros
#+BEGIN_SRC emacs-lisp :tangle yes
  ;; To save a macro, record it with C-x ( (start) and C-x ) (stop),
  ;; give it a name with C-x C-k n (C-k is for maKro) and
  ;; insert it in this file with insert-kbd-macro.
  ;; Then you execute it mapping it to a key! 😊

  ;; Example macro: Mark todos as done
  (fset 'org-mark-as-done
     (lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item (quote ("d" 0 "%d")) arg)))
     (fset 'foobar-was-here
     [?A ?  ?- ?- ?  ?f ?o ?o ?b ?a ?r ?  ?e ?a backspace backspace ?a backspace ?w ?a ?s ?  ?h ?e ?r ?e ?! escape ?\C-a])

  ;; Quicker replies in Twittering-mode.
  (fset 'my-twittering-mode-reply-to-user
   (lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item (quote ([3 return 3 18 67] 0 "%d")) arg)))

#+END_SRC
* Twittering mode
  Use Twitter from within Emacs!
  #+BEGIN_SRC emacs-lisp :tangle yes
    (use-package twittering-mode
    :bind (:map twittering-mode-map
       ("C-c r" . my-twittering-mode-reply-to-user)
       ("C-c f" . twittering-favorite)
       ("C-c n" . twittering-native-retweet)))

    ;; WIP, needs A LOT of remapping
    ;; Use evil-mode to navigate twittering's frame
    ;; (evil-set-initial-state 'twittering-mode 'emacs)

    ;; Adjust update interval in seconds. It's timeR, not time!
    (setq twittering-timer-interval 3600)

    ;; Display icons (if applicable)
    (setq twittering-icon-mode t)

    ;; Use a master password so you don't have to ask for authentication every time
    (setq twittering-use-master-password t)
  #+END_SRC

  #+RESULTS:
  : t

* Packages saved for later need
** Perspective
# ** Perspective
#    Switch between named "perspectives" of the editor.
#    #+BEGIN_SRC emacs-lisp :tangle yes
#    (use-package perspective)
#    (persp-mode)
#    #+END_SRC
